
; Colors
WHITE = $01
BLACK = $00

BORDER_COLOUR_LOCATION = $d020
BACKGROUND_COLOUR_LOCATION = $d021

;characters
SPACE_CHAR = $20

; Memory ranges
VRAM_START_ADDRESS = $0400
VRAM_END_ADDRESS = $0800
HIGH_MEMORY_START_LOCATION =  $C000
HIGH_MEMORY_END_LOCATION =  $FFFF
ZERO_PAGE_START_LOCATION = $02
ZERO_PAGE_END_LOCATION = $FF

; PLAYER LOCATION
PLAYER_X_ADDRESS_LOW = $d000  
PLAYER_Y_ADDRESS = $d001
PLAYER_MOVE_SPEED = 3
PLAYER_MAX_X = 250
PLAYER_MIN_X = 30

PLAYER_FLIPPED_LOCATION = ZERO_PAGE_START_LOCATION
UP = 0
DOWN = 1

BULLET_MOVE_SPEED = 4
BULLET_X_ADDRESS_LOW = $d004 
BULLET_Y_ADDRESS = $d005
BULLET_IS_FIRING_LOCATION = 251
BULLET_DIRECTION_LOCATION = 252


ENEMY_1_X_ADDRESS = $d006 
ENEMY_1_Y_ADDRESS = $d007


; Types
TRUE = 1
FALSE = 0

; SPRITE POINTERS
PLAYER_ADDRESS = $07F8
PLAYER_UP_VALUE = $28
PLAYER_DOWN_VALUE = $29
PLAYER_BULLET_SPRITE_ADDRESS = $07FA
PLAYER_BULLET_SPRITE_VALUE = $2A

ENEMY_1_SPRITE_ADDRESS = $07FB

ROBOT_ENEMY_F1_SPRITE_VALUE = $2b
ROBOT_ENEMY_RESET_FRAME = $2f

EXPLOSION_F1_SPRITE_VALUE = $2f
EXPLOSION_RESET_FRAME = $32

ROBOT_ENEMY_CURRENT_FRAME_ADDRESS = ENEMY_1_SPRITE_ADDRESS

; ZERO PAGE ADDRESSES

TEMP1 = ZERO_PAGE_START_LOCATION + 1
TEMP2 = ZERO_PAGE_START_LOCATION + 2
TEMP3 = ZERO_PAGE_START_LOCATION + 3
ENEMY1_HIT = ZERO_PAGE_START_LOCATION + 4
GAMEPLAY_TIMER_ADDRESS = ZERO_PAGE_START_LOCATION + 5
ANIMATION_TIMER_ADDRESS = ZERO_PAGE_START_LOCATION + 6
PLAYER_IN_DEATH_STATE = ZERO_PAGE_START_LOCATION + 7


; 16 it addressses

SCORE_ADDRESS_LOW = HIGH_MEMORY_START_LOCATION

SCORE_ADDRESS_HIGH = HIGH_MEMORY_START_LOCATION + 1
LIVES_ADDRESS_LOW = HIGH_MEMORY_START_LOCATION + 2

DEATH_TIMER_LOW = HIGH_MEMORY_START_LOCATION + 4


